spring:
  cloud:
    gateway:
      #SSL相关
      ssl:
        #是否使用自动生成的证书  该功能仅建议开发/测试使用临时性证书
        auto-generate-cert-enabled: false
        #支持的 SSL 协议版本，多个用逗号分隔
        protocols: "TLSv1.2,TLSv1.3"
        #域名
        generate-cert-domain: "localhost"

sa-token:
  #不打印sa-token logo
  is-print: false
  #开启该注解 需配合下游服务实例同时配置才能生效  生效后 无法绕过gateway直接请求实例
  checkSameToken: true